# Generated by Django 5.2.11 on 2026-03-17 07:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('TECH', 'Tech'), ('CULTURAL', 'Cultural'), ('SPORTS', 'Sports'), ('GENERAL', 'General')], default='GENERAL', max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='club_images/')),
                ('approved', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organizer', models.OneToOneField(blank=True, limit_choices_to={'role': 'ORGANIZER'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organized_club', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
